recipeFinder/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'recipeFinder'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('detail/<str:id>/<str:course>/', login_required(views.recipe_detail), name='recipe_detail'),
    path('detail/<str:id>', login_required(views.recipe_detail), name='recipe_detail'),
    path('recipe_search', login_required(views.recipe_search), name='recipe_search'),
    path('suggestions', login_required(views.suggestions), name='suggestions')
]

recipeFinder/templates/recipeFinder/detail.html
{% extends "base.html" %}
{% load mathfilters %}

{% block content %}

<article id="small-panel">

    {% if course %}
        <form action="{% url 'recipeFinder:recipe_detail' id course.0 %}" method="post">
    {% else %}
        <form action="{% url 'recipeFinder:recipe_detail' id %}" method="post">
    {% endif %}
    <!-- csrf_token to protect against XSS attacks -->
    {% csrf_token %}
    <!-- Display different icons depending on whether the user has the recipe saved-->
    {% load static %}
    {% if is_saved %}
        <button type = submit title = "Save recipe" class = "savebutton"><img src="{% static 'img/save_icon_active.png' %}" /></button>
    {% else %}
        <button type = submit title = "Save recipe" class = "savebutton"><img src="{% static 'img/save_icon_inactive.png' %}" /></button>
    {% endif %}
    </form>

    <header>
        <h3>{{ name }}</h3>
    </header>

    <center>
    Yield: {{ yield }}<br>
    Prep Time: {{ totalTime }}<br>
    {% if course %}
    Category: {{ course }}
    {% else %}
    Category: None
    {% endif %}
    </center>
    <br>
    <!-- display star ratings -->
    <div class="star-ratings">
        <div class="star-ratings-top" style="width:{% if rating %}{{ rating|div:5.0|mul:100 }}{% else %}0{% endif %}%">
            <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
        <div class="star-ratings-bottom"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
    </div>

    <!-- display the first large or small thumbnail, if available -->
    {% if images.0.hostedLargeUrl %}
        <br>
        <img src = {{ images.0.hostedLargeUrl }} class = "center" >
        <br>
    {% elif images.0.hostedSmallUrl %}
        <br>
        <img src = {{ images.0.hostedSmallUrl }} class = "center" >
        <br>
    {% endif %}

    <!-- display ingredients -->
    <ul class="center">
    {% for line in ingredientLines %}
        <li>
        {{line}}
        </li>
    {% endfor %}
    </ul>

    {% if source.sourceRecipeUrl %}
        <p><a href="{{ source.sourceRecipeUrl }}">{{ source.sourceRecipeUrl }}</a></p>
    {% endif %}

    <form action="{% url 'recipeFinder:index' %}" method="post">
		{% csrf_token %}
		<input type="submit" value="Back to Search Results" />
	</form>

</article>

{% endblock %}

<script>
$(document).ready(function() {
  // get span width of the filled ratings
  var star_rating_width = $('.star-ratings-top').width();
  // set container to span width for mobile correctness
  $('.star-ratings').width(star_rating_width);
});
</script>

recipeFinder/templates/recipeFinder/not_found.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
   <header>
      <h3>Sorry, we couldn't find any recipes for you.</h3>
      {% if too_few %}
         <p> Try adding more items to your inventory.</p>
      {% else %}
         <p> Try broadening your search by selecting fewer ingredients.</p>
      {% endif %}
   </header>

	<form action="{% url 'recipeFinder:index' %}" method="get">
		<!-- csrf_token not required in a GET form -->
		<input type="submit" value="Back to Recipe Finder" />
	</form>
</article>

{% endblock %}

recipeFinder/templates/recipeFinder/recipe_search.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
    {% if inventory_items %}
    <header>
        <h3>Select items from your inventory.</h3>
    </header>
    {% endif %}
    <form action="{% url 'recipeFinder:recipe_search' %}" method="post">
        {% csrf_token %}
        {% for item in inventory_items %}
        <input type="checkbox" name="checked" id="item{{ forloop.counter }}"
               value="{{ item }}"/>
        <label for="item{{ forloop.counter }}">{{ item }}</label> <br/>
        {% endfor %}
        <br>
    {% if inventory_items %}
        <header>
            <h3>Enter additional ingredients below.</h3>
        </header>
    {% else %}
        <header>
            <h3>Type in the ingredients that you want to make a recipe with.</h3>
        </header>
    {% endif %}
        {{ ingredient_formset.management_form }}

        {% for ingredient_form in ingredient_formset %}
        <div class="ingredient-formset">
            <p>
                {{ ingredient_form.item }}
                {% if ingredient_form.value.errors %}
                {% for error in ingredient_form.value.errors %}
                {{ error|escape }}
                {% endfor %}
                {% endif %}
            </p>
        </div>
        {% endfor %}
        <br>
        <br>
        In the mood for anything in particular?<br>
        <input type="text" name="search_phrase" value="">
        <br>
        <br>
        <input type="submit" value="Search!"/>
        <br>
        <br>
    </form>
    <form action="{% url 'recipeFinder:suggestions' %}" method="get">
           <input type="submit" value="I'm feeling lucky!" />
    </form>
</article>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/static/scripts/jquery.formset.js"></script>
<script>
    // add an autocomplete handler to a form
    function attachAutocomplete(form) {

        form
        // don't leave form field on tab-selecting an item
        .on("keydown", function(event) {
            if (event.keyCode === $.ui.keyCode.TAB &&
                $(this).autocomplete("instance").menu.active) {
                    event.preventDefault();
                }
        })
        .autocomplete({
            formatItem: function(row) {
                return row[1];
            },
            autoFocus: true,
            minLength: 1,
            delay: 0,
            source: function (request, response) {
                var resultLimit = 8;
                var results = $.map({{ food_suggestions|safe }}, function (food) {
                    if (food.toUpperCase().indexOf(request.term.toUpperCase()) === 0) {
                        return food;
                    }
                });
            response(results.slice(0, resultLimit));
            }
        });
    }
    // initialize the very first autocomplete handler
    $(function() {
    attachAutocomplete($('.autocomplete'));
    })

    $('.ingredient-formset').formset({
        addText: 'Add Ingredient',
        deleteText: 'Remove Ingredient',
        added: function(row) {
            var form = row.find('.autocomplete');
            // unbind previous autocomplete handlers
            form.unbind();
            // add new autocomplete handler
            attachAutocomplete(form);
            // set focus to new form
            form.focus();
        }
    });

</script>

{% endblock %}

recipeFinder/templates/recipeFinder/results.html
{% extends "base.html" %}
{% load mathfilters %}

{% block content %}

<article>
    <header>
        <div style="display: block;">
        <span>Recipe Finder</span>
        <input type="button" onclick="window.location.href ='{% url 'recipeFinder:recipe_search' %}'; return false;" value="Back to Recipe Finder"
            style=" float: right;
                height: 35px;
                border-radius: 5px;
                background-color: #f76707;
                border: none;
                color: #f2f2f2;
                font-size: .7em;
                clear:left;"
                />
        {% if suggested %}
        <input type="button" onclick="window.location ='{% url 'recipeFinder:suggestions' %}'; return false;" value="Try Again" 
            style=" float: right;
                height: 35px;
                border-radius: 5px;
                background-color: #e9ecef;
                border: none;
                margin-right:15px;
                color: #000;
                font-size: .7em;
                clear:left;"
                />
         {% endif %}
    </header>

    <!-- debug -->
    {% if criteria.maxResults %}
    <center> <p> Displaying up to {{criteria.maxResults}} search results
        {% if criteria.terms %}
        for "
        {% for term in criteria.terms %}
            {{term}}
            {% if not forloop.last %}
                 +
            {% endif %}
        {% endfor %}
        "
        {% endif %}
    </p> </center>
    <br>
    {% endif %}

    <section>
        <div style="display: block; margin: 0 auto;">
        <!-- display all matched recipes -->
        {% for match in matches %}
            <div class="recipe-preview">
                <h4>{{ match.recipeName }}</h4>
                <div class="star-ratings">
                    <div class="star-ratings-top" style="width:{% if match.rating %}{{ match.rating|div:5.0|mul:100 }}{% else %}0{% endif %}%">
                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
                    <div class="star-ratings-bottom"><span>★</span><span>★</span><span>★</span><span>★</span><span>★</span></div>
                </div>
                <div class="recipe-image" style="height:125px">
                <!-- display first thumbnail if available -->
                {% if match.smallImageUrls %}
                    <img src="{{ match.smallImageUrls.0 }}">
                {% else %}
                    <div class="no-image">
                    <p>No Image</p>
                    <i class="fas fa-camera fa-2x" style="margin:0 auto;"></i>
                    </div>
                {% endif %}
                </div>
                 <div style="margin-top: 5px">
                {% if match.attributes.course.0 %}
                    <a href = "{% url 'recipeFinder:recipe_detail' match.id match.attributes.course.0 %}">View Recipe</a>
                {% else %}
                    <a href = "{% url 'recipeFinder:recipe_detail' match.id %}">View Recipe</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
</article>

{% endblock %}

<script>
$(document).ready(function() {
  // get span width of the filled ratings
  var star_rating_width = $('.star-ratings-top').width();
  // set container to span width for mobile correctness
  $('.star-ratings').width(star_rating_width);
});
</script>