recipes/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'recipes'
urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:pk>/', login_required(views.RecipeView.as_view()), name='detail'),
    path('new_recipe/', login_required(views.add_recipe), name='new_recipe'),
    path('<int:pk>/edit', login_required(views.add_recipe), name='edit_recipe'),
    path('<int:pk>/delete', login_required(views.delete_recipe), name='delete_recipe'),
    path('<int:pk>/create_grocery_list/', login_required(views.create_grocery_list), name='create_grocery_list')
]

recipes/models.py
from django.db import models
from django.forms import ModelForm, ModelChoiceField
from django.urls import reverse
from inventory.models import InventoryItem
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

CATEGORY_CHOICES = (
	('', ''),
    ('Appetizers', 'Appetizers'),
    ('Soups', 'Soups'),
    ('Salads', 'Salads'),
    ('Breads', 'Breads'),
    ('Main Dishes', 'Main Dishes'),
    ('Side Dishes', 'Side Dishes'),
    ('Desserts', 'Desserts'),
    ('Breakfast and Brunch', 'Breakfast and Brunch'),
    ('Lunch and Snacks', 'Lunch and Snacks'),
    ('Beverages', 'Beverages'),
    ('Cocktails', 'Cocktails'),
    ('Condiments and Sauces', 'Condiments and Sauces'))

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(0, filename) #instance.user.id

class Recipe(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max file size is %sMB" % str(megabyte_limit))

    user = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    date = models.DateTimeField(null=True, blank=True)
    prepTime = models.CharField(max_length=20, blank=True, null=True)
    servings = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(max_length=25, choices=CATEGORY_CHOICES, null=True)
    instructions = models.TextField(blank=True, null=True)
    yummlyId = models.CharField(max_length=100, null=True, blank=True)
    externalLink = models.URLField(max_length=200,null=True, blank=True)
    image = models.ImageField(upload_to=user_directory_path, null=True, blank=True, validators=[validate_image])
    imageUrl = models.URLField(max_length=200,null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    pass

class RecipeIngredients(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	ingredient = models.CharField(max_length=100, null=False, blank=False)
	inventoryItem = models.ForeignKey(InventoryItem, on_delete=models.CASCADE, null=True, blank=True)

	def __str__(self):
	    return self.name

	pass

recipes/templates/recipes/index.html
{% extends "base.html" %}

{% block content %}

<article>
    <header>
        <div style="display: block;">
            <span>My Recipes</span>
            <input type="button" onclick="window.location.href ='{% url 'recipes:new_recipe' %}'; return false;" value="Add New Recipe"/>
            <input class="grey" type="button" onclick="window.location.href ='{% url 'recipeFinder:recipe_search' %}'; return false;" value="Find New Recipes" />
        </div>
    </header>

    {% if all_recipes %}
    <section>
        <div style="display: block; margin: 0 auto;">
        {% for recipe in all_recipes %}
            <div class="recipe-preview">
                <h4>{{ recipe.name }}</h4>
                <div class="recipe-image" style="height:125px">
                {% if recipe.image %}
                    <img src="{{ recipe.image.url }}" />
                {% elif recipe.imageUrl %}
                    <img src="{{ recipe.imageUrl }}" />
                {% else %}
                    <div class="no-image">
                    <p>No Image</p>
                    <i class="fas fa-camera fa-2x" style="margin:0 auto;"></i>
                    </div>
                {% endif %}
                </div>
                <div style="margin-top: 5px">
                    <a href="{% url 'recipes:detail' recipe.id %}">View Recipe</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
    {% else %}
    <section>
        <p>
        <center>
            You have no recipes available.<br>
            Try <a href="{% url 'recipes:new_recipe' %}">adding a new recipe</a> or <a href="{% url 'recipeFinder:recipe_search' %}">searching</a> for new ones!<br><br>
        </center>
        </p>
    </section>
    {% endif %}

</article>

{% endblock %}

recipes/templates/recipes/new_recipe.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
    <header>
        {% if is_edit %}
        <h3> Edit Recipe </h3>
        {% else %}
        <h3> Add A New Recipe </h3>
        {% endif %}
    </header>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <strong>
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
            </p></strong>
        {% endfor %}
    </ul>
    {% endif %}

    {% if is_edit %}
    <form action="{% url 'recipes:edit_recipe' id %}" method="post" enctype="multipart/form-data">
    {% else %}
    <form action="/recipes/new_recipe/" method="post" enctype="multipart/form-data">
    {% endif %}
        {% csrf_token %}

        <p><label for="recipe_name">Name:</label>{{ form.name }}</p>

        <p><label for="recipe_prep">Prep Time:</label>{{ form.prepTime }}</p>

        <p><label for="recipe_servings">Yield:</label>{{ form.servings }}</p>

        <p><label for="recipe_category">Category:</label>{{ form.category }}</p>

        <p>
            <label for="recipe_image">Image:</label>
            <br><span class="helptext">
            Add an image to your recipe! The upload only accepts .png, .gif, .jpg, and .jpeg
            files with a max size of 2MB.
            </span>

            {% if form.image.errors %}
                <p style="color: red;">
                {% for error in form.image.errors %}
                    {{ error|escape }}
                {% endfor %}
                </p>
            {% endif %}

            <p>{{ form.image }}</p>

            <div id="image-holder"></div>
        </p>

        <p>
            <label for="recipe_ingredients">Ingredients:</label><br/>
            <span class="helptext">
            Add ingredients to your recipe and connect them to items in your
            inventory to get meal suggestions.
            </span><br/>
            {{ ingredient_formset.management_form }}

            {% for ingredient_form in ingredient_formset %}
                <div class="ingredient-formset">
                    <p>
                        {{ ingredient_form.value }}
                        {% if ingredient_form.value.errors %}
                            {% for error in ingredient_form.value.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                        <!--{{ ingredient_form.inventoryItem }}-->
                    </p>
                </div>
            {% endfor %}
        </p>

        <p><label for="recipe_instructions">Instructions:</label>{{ form.instructions }}</p>

        <p><label for="recipe_external">External Link:</label><br/>{{ form.externalLink }}</p>

        <input type="submit" value="Save" /><br/><br/>

        {% if is_edit %}
        <input type="button" onclick="window.location.href ='{% url 'recipes:detail' id %}'; return false;" value="Cancel" />
        {% else %}
        <input type="button" onclick="window.location.href ='{% url 'recipes:index' %}'; return false;" value="Cancel" />
        {% endif %}
    </form>
</article>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/static/scripts/jquery.formset.js"></script>
<script>
    function split(val) {
      return val.split(" ");
    }
    function lastTerm(term) {
      return split(term).pop();
    }
    // add an autocomplete handler to a form
    function attachAutocomplete(form) {

        form
        // don't leave form field on tab-selecting an item
        .on("keydown", function(event) {
            if (event.keyCode === $.ui.keyCode.TAB &&
                $(this).autocomplete("instance").menu.active) {
                    event.preventDefault();
                }
        })
        .autocomplete({
            formatItem: function(row) {
                return row[1];
            },
            autoFocus: true,
            minLength: 1,
            delay: 0,
            source: function (request, response) {
                var resultLimit = 8;
                // filter out 'starting with' terms
                var results = $.map({{ food_suggestions|safe }}, function (food) {
                    if (food.toUpperCase().indexOf(lastTerm(request.term).toUpperCase()) === 0) {
                        return food;
                    }
                });
                // limit results to resultLimit
                results = results.slice(0, resultLimit);
                //delegate back to autocomplete, for last term only
                response( $.ui.autocomplete.filter(
                results, lastTerm(request.term)));
                },
                focus: function() {
                    // prevent value inserted on focus
                    return false;
                },
                select: function(event, ui) {
                    var terms = split(this.value);
                    // remove the current input
                    terms.pop();
                    // add the selected item
                    terms.push(ui.item.value);
                    // add placeholder to get the space at the end
                    terms.push("");
                    this.value = terms.join(" ");
                    return false;
                }
            });
    }
    // initialize the very first autocomplete handler
    $(function() {
    attachAutocomplete($('.autocomplete'));
    })

    $('.ingredient-formset').formset({
        addText: 'Add Ingredient',
        deleteText: 'Remove Ingredient',
        added: function(row) {
            var form = row.find('.autocomplete');
            // unbind previous autocomplete handlers
            form.unbind();

            // add new autocomplete handler
            attachAutocomplete(form);
            // set focus to new form
            form.focus();
        }
        });
</script>
<script>
$("#id_image").on('change', function () {

     var imgPath = $(this)[0].value;
     var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
     var image_holder = $("#image-holder");
     image_holder.empty();

     if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
         if (typeof (FileReader) != "undefined") {

            var reader = new FileReader();
            reader.onload = function (e) {
                $("<img />", {"src": e.target.result,
                              "style": "width:100%;"}).appendTo(image_holder);
            };

            image_holder.show();
            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
         } else {
             alert("This browser does not support FileReader.");
         }
     }
 });
</script>

{% endblock %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">

    <form action="{% url 'recipes:delete_recipe' recipe.id %}" method="post">
	    <!-- csrf_token to protect against XSS attacks -->
	    {% csrf_token %}
        {% load static %}
        <button type = submit title = "Delete recipe" class = "savebutton"><img src="{% static 'img/save_icon_active.png' %}" /></button>
    </form>

    <header>
        <h3>{{ recipe.name }}</h3>
    </header>

	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	        <strong>
	        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
	        </p></strong>
	    {% endfor %}
	</ul>
	{% endif %}


    <center>
    Yield: {{ recipe.servings }}<br>
	Prep time: {{ recipe.prepTime }}<br>
	Category: {{ recipe.category }}
    </center>

	<!-- user-uploaded ImageField -->
	{% if recipe.image %}
	    <br>
	    <img src = {{ recipe.image.url }} class = "center" >
	    <br>
	{% endif %}

	<!-- Yummly image url -->
	{% if recipe.imageUrl %}
	<br>
	<img src = {{ recipe.imageUrl }} class = "center" >
	<br>
	{% endif %}

	<!-- display ingredients -->
	{% if ingredients %}
	<ul class="center">
		{% for ingredient in ingredients %}
		<li>{{ ingredient.ingredient }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% if recipe.instructions %}
		<div style="white-space: pre-line; text-indent: 0;">
			{{ recipe.instructions }}
		</div>
	{% endif %}

	{% if recipe.externalLink %}
		<p>External Link:<br>
			{% if recipe.yummlyId %}
			<span class="helptext">
				This recipe was imported using a Yummly search. Follow the external link to view
				instructions on how to make this recipe!
			</span>
			{% endif %}
			<a href="{{ recipe.externalLink }}">{{ recipe.externalLink }}</a>
		</p>	
	{% endif %}	

	<br>

	{% if not recipe.yummlyId %}
	<form action="{% url 'recipes:edit_recipe' recipe.id %}">
		<input type="submit" value="Edit Recipe" /><br></br>
	</form>
	{% endif %}
	
	<form action="{% url 'recipes:create_grocery_list' recipe.id %}">
		<input type="submit" value="Create Grocery List" /><br></br>
	</form>
	


	<input type="button" onclick="window.location.href ='{% url 'recipes:index' %}'; return false;" value="Back" />

</article>

{% endblock %}