groceryList/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'groceryList'
urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:pk>/', login_required(views.GroceryListView.as_view()), name='detail'),
    path('new/', login_required(views.NewGroceryListView.as_view()), name='new'),
    path('new/<str:food_name>/<str:barcode>', login_required(views.NewGroceryListView.as_view()), name='new'),
    path('add/', login_required(views.add), name='add'),
    path('add_inv_item/<int:pk>', login_required(views.add_inv_item), name='add_inv_item'),
    path('<int:pk>/update', login_required(views.update), name='update'),
    path('<int:pk>/<int:id>/confirm', login_required(views.confirm_item), name='confirm_item'),
    path('<int:pk>/<int:id>/delete', login_required(views.delete_item), name='delete_item'),
    path('<int:pk>/delete', login_required(views.delete_list), name='delete_list')
]

groceryList/templates/groceryList/detail.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">

    <form action="{% url 'groceryList:delete_list' grocery_list.id %}" method="post"
        <!-- csrf_token to protect against XSS attacks -->
        {% csrf_token %}
        {% load static %}
        <button type = submit title = "Delete Grocery List" class = "savebutton"><img src="{% static 'img/save_icon_active.png' %}" /></button>
    </form>

    <header>
        <h3>{{ grocery_list.name }}</h3>
    </header>
    
    {% if messages %}
       {% for message in messages %}
          <div {% if message.tags %} style="color: #c92a2a;" class="{{ message.tags }}"{% endif %}>{{ message }}
          </div><br>
       {% endfor %}
    {% endif %}
    
    <span class="helptext" style="text-align: center;">
        Manage your grocery list by adding items, <a href="{% url 'barcodeScan:index' 'g' %}">scanning items</a>, deleting items, and marking items as added to your inventory.
    </span>
    <br>
    <br>

    <form action="{% url 'groceryList:update' grocery_list.id %}" method="post">
        {% csrf_token %}

        {% if grocery_items %}
        {% for item in grocery_items %}
        <div data-role="grocery_item">
            <label>{{ item.name }}</label><br>
            <input data-role="quantity" 
                type="number" 
                required 
                style="width:75%; text-align: right;" 
                min="1" 
                max="100" 
                value="{{ item.quantity }}" 
                {% if item.confirmed %} disabled {% endif %}
                name="quantity_item_{{ item.id }}"
                id="quantity_item_{{ item.id }}">
            <div style="float:right;">

                <i aria-hidden="true"
                   data-action="confirm"
                   data-actionable="{{ item.confirmed|yesno:'False,True' }}"
                   data-list-id="{{ grocery_list.id }}"
                   data-grocery-item-id="{{ item.id }}"
                   style="margin-right: 10px; margin-top: 10px;
                    {% if item.confirmed %}
                    color:#adb5bd;
                    {% else %}
                    color:#2f9e44;
                    {% endif %}"
                   class="fas fa-check fa-lg">
                </i>

                <i aria-hidden="true"
                   data-action="delete"
                   data-actionable="{{ item.confirmed|yesno:'False,True' }}"
                   data-list-id="{{ grocery_list.id }}"
                   data-grocery-item-id="{{ item.id }}"
                   style="margin-right: 10px; margin-top: 10px;
                    {% if item.confirmed %}
                    color:#adb5bd;
                    {% else %}
                    color:#c92a2a;
                    {% endif %}"
                   class="far fa-trash-alt fa-lg" >
                </i>
            </div>
            <br><br>
        </div>
        {% endfor %}
        {% endif %}

        <hr>
        <p><label>Item:</label><br>
            <span class="helptext">
                Add items to your grocery list and connect them to inventory item to get meal suggestions and automatically update inventory quantities.
            </span><br>
            {{ item_form.name }}
            <!--{{ item_form.inventory_item }}-->
        </p>
        <p><label>Quantity:</label>{{ item_form.quantity }}</p>

        <input type="submit" value="Save" />
    </form>

    <br>
    <input type="submit" onclick="window.location.href ='{% url 'barcodeScan:index' %}'; return false;" value="Scan Item" />

    <br><br>
    <input type="button" onclick="window.location.href ='{% url 'groceryList:index' %}'; return false;" value="Back" />

</article>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
$(document).ready(function() {
    $('[data-role=grocery_item]').on('click', '[data-action=delete]', function(e){
        var $grocery_item = $(e.delegateTarget);
        var $delete = $(e.currentTarget);
        var grocery_list_id = $delete.data("list-id");
        var grocery_item_id = $delete.data("grocery-item-id");
        var actionable = $delete.data("actionable");

        if (actionable == 'True') {
            var delete_path = "/groceryList/" + grocery_list_id + "/" + grocery_item_id + "/delete"
            $.get(delete_path, function(data) {
                $grocery_item.remove();
            });
        }
    });
});

$(document).ready(function() {
    $('[data-role=grocery_item]').on('click', '[data-action=confirm]', function(e){
        var $grocery_item = $(e.delegateTarget);
        var $quantity = $grocery_item.find('[data-role=quantity]');
        var $delete = $grocery_item.find('[data-action=delete]');
        var $confirm = $(e.currentTarget);
        var grocery_list_id = $confirm.data("list-id");
        var grocery_item_id = $confirm.data("grocery-item-id");
        var actionable = $confirm.data("actionable");

        if (actionable == 'True') {
            var confirm_path = "/groceryList/" + grocery_list_id + "/" + grocery_item_id + "/confirm"
            $.get(confirm_path, {quantity: $quantity.val()}, function(data) {
                $quantity.attr("disabled", "true");
                // makes it so that you cannot delete the item or update the quantity
                $confirm.attr("data-actionable", "False");
                $delete.attr("data-actionable", "False");

                // updates the color of the trash and check mark icon since a full
                // postback doesn't happen
                $confirm.css('color', '#adb5bd');
                $delete.css('color', '#adb5bd');
            });
        }
    });
});
</script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $( function() {
    $( "#{{ item_form.name.id_for_label }}" )
		// don't leave form field on tab-selecting an item
        .on("keydown", function(event) {
            if (event.keyCode === $.ui.keyCode.TAB &&
                $(this).autocomplete("instance").menu.active) {
                    event.preventDefault();
                }
        })
        .autocomplete({

			autoFocus: true,
			minLength: 1,
			delay: 0,
			source: function (request, response) {
				var resultLimit = 8;
				var results = $.map({{ food_suggestions|safe }}, function (food) {
				if (food.toUpperCase().indexOf(request.term.toUpperCase()) === 0) {
					return food;
				}
			});
		response(results.slice(0, resultLimit));
		}
    });
    } );
</script>
{% endblock %}

groceryList/templates/groceryList/index.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
    <header>
        <h3>Grocery Lists</h3>
    </header>

    {% if all_grocery_lists %}
        <center>Here are your grocery lists:</center>
        <ul>
        {% for list in all_grocery_lists %}
            <li><a href="{% url 'groceryList:detail' list.id %}">{{ list.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <center>No grocery lists are available.</center><br>
    {% endif %}

    <input type="submit" onclick="window.location.href ='{% url 'groceryList:new' %}'; return false;" value="Add New Grocery List" /> 
</article>

{% endblock %}

groceryList/templates/groceryList/new.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
    <header>
        <h3>Add New Grocery List</h3>
    </header>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <strong>
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
            </p></strong>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="{% url 'groceryList:add' %}" method="post">
        {% csrf_token %}
        {% if food_name %}
            <!-- Used to add items from the barcode scanner to the grocery list -->
            <input type="hidden" name="food_name" value="{{ food_name }}">
            <input type="hidden" name="barcode" value="{{ barcode }}">
        {% endif %}
        {{ form }}
        <br>
        <br>
        <input type="submit" value="Submit" />
    </form>

    <br>
    <input type="button" onclick="window.location.href ='{% url 'groceryList:index' %}'; return false;" value="Cancel" />

</article>

{% endblock %}

groceryList/templates/groceryList/recipe.html
{% extends "base.html" %}

{% block content %}

<article id="small-panel">
    <header>
        <h3>{{ recipe.name }}</h3>
    </header>

<ul>
{% for fooditem in recipe.fooditems.all %}
    <li>Recipe calls for {{ fooditem.quantity }} {{ fooditem.name }}</li>
{% endfor %}
</ul>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <strong>
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
        </p></strong>
    {% endfor %}
</ul>
{% endif %}

<form action="{% url 'groceryList:add_to_recipe' pk=recipe.id %}" method="post">
{% csrf_token %}
    {{ form }} <br>
    <input type="submit" value="Submit" />
</form>

<a href="{% url 'groceryList:index' %}">View all grocery lists</a>

</article>

{% endblock %}