dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'dashboard'
urlpatterns = [
    path('', login_required(views.index), name='index'),
]

groceryList/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'groceryList'
urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:pk>/', login_required(views.GroceryListView.as_view()), name='detail'),
    path('new/', login_required(views.NewGroceryListView.as_view()), name='new'),
    path('new/<str:food_name>/<str:barcode>', login_required(views.NewGroceryListView.as_view()), name='new'),
    path('add/', login_required(views.add), name='add'),
    path('add_inv_item/<int:pk>', login_required(views.add_inv_item), name='add_inv_item'),
    path('<int:pk>/update', login_required(views.update), name='update'),
    path('<int:pk>/<int:id>/confirm', login_required(views.confirm_item), name='confirm_item'),
    path('<int:pk>/<int:id>/delete', login_required(views.delete_item), name='delete_item'),
    path('<int:pk>/delete', login_required(views.delete_list), name='delete_list')
]

inventory/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'inventory'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('add/', login_required(views.add_view), name='add'),
    path('remove/<int:pk>', login_required(views.remove_view), name='remove'),
    path('update/<int:pk>/<int:quantity>', login_required(views.update_view), name='update'),
]

recipes/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'recipes'
urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('<int:pk>/', login_required(views.RecipeView.as_view()), name='detail'),
    path('new_recipe/', login_required(views.add_recipe), name='new_recipe'),
    path('<int:pk>/edit', login_required(views.add_recipe), name='edit_recipe'),
    path('<int:pk>/delete', login_required(views.delete_recipe), name='delete_recipe'),
    path('<int:pk>/create_grocery_list/', login_required(views.create_grocery_list), name='create_grocery_list')
]

stats/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'stats'
urlpatterns = [
    path('', login_required(views.statsHandler), name='index')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    	<title>MyMeal</title>
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="/static/css/stylesheet.css" />
      <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">
    	<!-- used for importing icons -->
    	<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    </head>
    <body>
        <div class="navbar" id="myNavbar">
        	<!-- TODO; implement collapsing navigation -->
        	<div id="nav-left">
              <a class="logo" href= "{% url 'dashboard:index' %}">
                <img src="/static/img/MyMealFinal_Orange.png" style="height:40px;">
              </a>
        	  	<a class="directory" href="{% url 'inventory:index' %}">Inventory</a>
        	  	<a class="directory" href="{% url 'recipes:index' %}">Recipes</a>
        	  	<a class="directory" href="{% url 'groceryList:index' %}">Grocery Lists</a>
                <a class="directory" href="{% url 'stats:index' %}">Stats</a>
                <a class="directory" href="{% url 'auth_logout' %}" id="logout-mobile">Log Out</a>
        	</div>
          	<div id="nav-right">
          		<a class="directory" href="{% url 'auth_logout' %}" id="logout">Log Out</a>
                <a href="javascript:void(0);" class="menu" id= "dropdown-menu" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </a>
          		<!--<input type="text" placeholder="Search...">-->
        	</div>
        </div>

        <div id="main">
            <div id="content-wrapper">
        		{% block content %}{% endblock %}
          </div>
        </div>
    </body>
    <script>
        /* display responsive vertical menu for small screens */
        function myFunction() {
          const navbar = document.getElementById("myNavbar");
          document.getElementById("dropdown-menu").blur();
          if (navbar.className === "navbar") {
            navbar.className += " responsive";
            document.getElementById("main").style.marginTop='40px';
          } else {
            navbar.className = "navbar";
            document.getElementById("main").style.marginTop='100px';
          }
        }
    </script>
</html>